import { Log } from "./src/middleware/logger.js";

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJtZWRhcGF0aWpvZ2FzcmlwcmFuYXRoaS4yMy5lY2VAYW5pdHMuZWR1LmluIiwiZXhwIjoxNzgyMTk2ODg2LCJpYXQiOjE3ODIxOTU5ODYsImlzcyI6IkFmZm9yZCBNZWRpY2FsIFRlY2hub2xvZ2llcyBQcml2YXRlIExpbWl0ZWQiLCJqdGkiOiJmZjU0MjIyNC1mNGJiLTQwNjQtYTQwZS05NTMwMzA2ODY5NTMiLCJsb2NhbGUiOiJlbi1JTiIsIm5hbWUiOiJtZWRhcGF0aSBqb2dhIHNyaSBwcmFuYXRoaSIsInN1YiI6IjY0MmZmNGE4LWFmN2QtNDU1YS1hNjAwLTc3MGI3YzY2OWIyOSJ9LCJlbWFpbCI6Im1lZGFwYXRpam9nYXNyaXByYW5hdGhpLjIzLmVjZUBhbml0cy5lZHUuaW4iLCJuYW1lIjoibWVkYXBhdGkgam9nYSBzcmkgcHJhbmF0aGkiLCJyb2xsTm8iOiJhMjMxMjY1MTIxMDMiLCJhY2Nlc3NDb2RlIjoiTVRxeGFyIiwiY2xpZW50SUQiOiI2NDJmZjRhOC1hZjdkLTQ1NWEtYTYwMC03NzBiN2M2NjliMjkiLCJjbGllbnRTZWNyZXQiOiJ0TnVyR2NRS1F0ZGZTeGVaIn0.spphstjTmi68wQkjNZGmySN4VyBrbr86Pg3HaACEtds";
await Log(
  "backend",
  "info",
  "handler",
  "Test log message",
  token
);

console.log("Log sent");